name: hermes CI CD

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Change Directory
        run: |
          cd /home/dkadmin/hermes

      - uses: actions/checkout@v2


      - name: Docker Compose Up
        run: |
          sudo docker-compose up -d
