name: hermes CI CD

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v2

      - name: Change Directory
        run: |
          cd /home/dkadmin/actions-runner/_work/hermes/hermes                                                                                               

      - name: Docker Compose Up
        run: |
          sudo docker-compose up -d
